### Bo'lim yaratish
POST http://localhost:8080/department
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJyb2xlIjoiQURNSU4iLCJ2aXNpYmxlIjp0cnVlLCJzdXJuYW1lIjoiRG9lIiwibmFtZSI6IkpvaG4iLCJpZCI6MSwicG9zaXRpb24iOiJTb2Z0d2FyZSBEZXZlbG9wZXIiLCJlbWFpbCI6ImpvaG4uZG9lQGV4YW1wbGUuY29tIiwic3RhdHVzIjoiQUNUSVZFIiwic3ViIjoiam9obi5kb2VAZXhhbXBsZS5jb20iLCJpYXQiOjE3NDAxMjIzOTIsImV4cCI6MTc0MDIwODc5Mn0.JUg-S1VMLqfwYRI6aFihl5HL92qvDiKJqg83bgUA1es

{
  "title": "IT Department",
  "description": "Responsible for IT infrastructure",
  "phoneNumber": "+998902597890",
  "headOfDepartment": "Ali aliyev",
  "type": "TECHNICAL",
  "address": "Andijon shaxar"
}

### Barcha bo'limlarni olish
GET http://localhost:8080/department/all
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJyb2xlIjoiVVNFUiIsInZpc2libGUiOnRydWUsInN1cm5hbWUiOiJEb2UiLCJuYW1lIjoiSm9obiIsImlkIjoyLCJwb3NpdGlvbiI6IlNvZnR3YXJlIERldmVsb3BlciIsImVtYWlsIjoiam9obi5kb2VlQGV4YW1wbGUuY29tIiwic3RhdHVzIjoiQUNUSVZFIiwic3ViIjoiam9obi5kb2VlQGV4YW1wbGUuY29tIiwiaWF0IjoxNzQwMTIyNTAzLCJleHAiOjE3NDAyMDg5MDN9.7z5UKRM_8Ubgl8Ppz2O99XStT78fQ8kV5HdUfNx41OM

### ID bo'yicha bo'lim olish
GET http://localhost:8080/department/1
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJyb2xlIjoiQURNSU4iLCJ2aXNpYmxlIjp0cnVlLCJzdXJuYW1lIjoiRG9lIiwibmFtZSI6IkpvaG4iLCJpZCI6MSwicG9zaXRpb24iOiJTb2Z0d2FyZSBEZXZlbG9wZXIiLCJlbWFpbCI6ImpvaG4uZG9lQGV4YW1wbGUuY29tIiwic3RhdHVzIjoiQUNUSVZFIiwic3ViIjoiam9obi5kb2VAZXhhbXBsZS5jb20iLCJpYXQiOjE3MzkwMDQ3MjgsImV4cCI6MTczOTA5MTEyOH0.V-NL0olQN6hNuBqOMu-p8-ym0UdCx4X3Cq1g7zlu1AM

### Bo'limni yangilash
PUT http://localhost:8080/department/1
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJyb2xlIjoiQURNSU4iLCJ2aXNpYmxlIjp0cnVlLCJzdXJuYW1lIjoiRG9lIiwibmFtZSI6IkpvaG4iLCJpZCI6MSwicG9zaXRpb24iOiJTb2Z0d2FyZSBEZXZlbG9wZXIiLCJlbWFpbCI6ImpvaG4uZG9lQGV4YW1wbGUuY29tIiwic3RhdHVzIjoiQUNUSVZFIiwic3ViIjoiam9obi5kb2VAZXhhbXBsZS5jb20iLCJpYXQiOjE3MzkwMDQ3MjgsImV4cCI6MTczOTA5MTEyOH0.V-NL0olQN6hNuBqOMu-p8-ym0UdCx4X3Cq1g7zlu1AM

{
  "title": "Updated IT Department",
  "description": "Updated description"
}

### Bo'lim statusini yangilash
PUT http://localhost:8080/department/1/status
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJyb2xlIjoiQURNSU4iLCJ2aXNpYmxlIjp0cnVlLCJzdXJuYW1lIjoiRG9lIiwibmFtZSI6IkpvaG4iLCJpZCI6MSwicG9zaXRpb24iOiJTb2Z0d2FyZSBEZXZlbG9wZXIiLCJlbWFpbCI6ImpvaG4uZG9lQGV4YW1wbGUuY29tIiwic3RhdHVzIjoiQUNUSVZFIiwic3ViIjoiam9obi5kb2VAZXhhbXBsZS5jb20iLCJpYXQiOjE3Mzg5MjgxMTEsImV4cCI6MTczOTAxNDUxMX0.0U2752vhmXOpCdy0iDd0Mrn95hoZj4uBro2EFIBRuro

{
  "status": "CLOSED"
}

### Bo'limni o'chirish (mantiqiy)
PATCH http://localhost:8080/department/1/wipe
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJyb2xlIjoiQURNSU4iLCJ2aXNpYmxlIjp0cnVlLCJzdXJuYW1lIjoiRG9lIiwibmFtZSI6IkpvaG4iLCJpZCI6MSwicG9zaXRpb24iOiJTb2Z0d2FyZSBEZXZlbG9wZXIiLCJlbWFpbCI6ImpvaG4uZG9lQGV4YW1wbGUuY29tIiwic3RhdHVzIjoiQUNUSVZFIiwic3ViIjoiam9obi5kb2VAZXhhbXBsZS5jb20iLCJpYXQiOjE3MzkwMDQ3MjgsImV4cCI6MTczOTA5MTEyOH0.V-NL0olQN6hNuBqOMu-p8-ym0UdCx4X3Cq1g7zlu1AM

{
  "visible": true
}

### Bo'limni o'chirish (jismoniy)
DELETE http://localhost:8080/department/1
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJyb2xlIjoiQURNSU4iLCJ2aXNpYmxlIjp0cnVlLCJzdXJuYW1lIjoiRG9lIiwibmFtZSI6IkpvaG4iLCJpZCI6MSwicG9zaXRpb24iOiJTb2Z0d2FyZSBEZXZlbG9wZXIiLCJlbWFpbCI6ImpvaG4uZG9lQGV4YW1wbGUuY29tIiwic3RhdHVzIjoiQUNUSVZFIiwic3ViIjoiam9obi5kb2VAZXhhbXBsZS5jb20iLCJpYXQiOjE3MzkwMDQ3MjgsImV4cCI6MTczOTA5MTEyOH0.V-NL0olQN6hNuBqOMu-p8-ym0UdCx4X3Cq1g7zlu1AM

### Paginatsiya bilan bo'limlarni olish
GET http://localhost:8080/department/paged?page=1&size=10
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJyb2xlIjoiQURNSU4iLCJ2aXNpYmxlIjp0cnVlLCJzdXJuYW1lIjoiRG9lIiwibmFtZSI6IkpvaG4iLCJpZCI6MSwicG9zaXRpb24iOiJTb2Z0d2FyZSBEZXZlbG9wZXIiLCJlbWFpbCI6ImpvaG4uZG9lQGV4YW1wbGUuY29tIiwic3RhdHVzIjoiQUNUSVZFIiwic3ViIjoiam9obi5kb2VAZXhhbXBsZS5jb20iLCJpYXQiOjE3MzkwMDQ3MjgsImV4cCI6MTczOTA5MTEyOH0.V-NL0olQN6hNuBqOMu-p8-ym0UdCx4X3Cq1g7zlu1AM

### Filtr bo'yicha bo'limlarni olish
POST http://localhost:8080/department/filter?page=1&size=10
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJyb2xlIjoiQURNSU4iLCJ2aXNpYmxlIjp0cnVlLCJzdXJuYW1lIjoiRG9lIiwibmFtZSI6IkpvaG4iLCJpZCI6MSwicG9zaXRpb24iOiJTb2Z0d2FyZSBEZXZlbG9wZXIiLCJlbWFpbCI6ImpvaG4uZG9lQGV4YW1wbGUuY29tIiwic3RhdHVzIjoiQUNUSVZFIiwic3ViIjoiam9obi5kb2VAZXhhbXBsZS5jb20iLCJpYXQiOjE3MzkwMDQ3MjgsImV4cCI6MTczOTA5MTEyOH0.V-NL0olQN6hNuBqOMu-p8-ym0UdCx4X3Cq1g7zlu1AM
Content-Type: application/json

{
}