### Create Employee
POST http://localhost:8080/employee
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJyb2xlIjoiQURNSU4iLCJ2aXNpYmxlIjp0cnVlLCJzdXJuYW1lIjoiRG9lIiwiZGVwYXJ0bWVudElkIjoxLCJuYW1lIjoiSm9obiIsImlkIjoxLCJwb3NpdGlvbiI6IlNvZnR3YXJlIERldmVsb3BlciIsImVtYWlsIjoiam9obi5kb2VAZXhhbXBsZS5jb20iLCJzdGF0dXMiOiJBQ1RJVkUiLCJzdWIiOiJqb2huLmRvZUBleGFtcGxlLmNvbSIsImlhdCI6MTc0MDA4MzE2MiwiZXhwIjoxNzQwMTY5NTYyfQ.IA4gWUfgZgKM6dn4ohswn9AYdOKfIOPfBz8gpR1WpJc

{
  "name": "John",
  "surname": "Doe",
  "role": "ADMIN",
  "position": "Software Engineer",
  "status": "ACTIVE",
  "email": "asdda@example.com",
  "password": "securePassword",
  "departmentId": 1
}

### Get All Employees
GET https://rttm.astiedu.uz/api/employee/all
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJyb2xlIjoiU1VQRVJBRE1JTiIsInZpc2libGUiOnRydWUsInN1cm5hbWUiOiJZdWxkYXNoZXYiLCJkZXBhcnRtZW50SWQiOjEsIm5hbWUiOiJBdmF6YmVrIiwiaWQiOjEsInBvc2l0aW9uIjoiV2ViLWRpemF5bmVyIiwiZW1haWwiOiJhdmF6YmVrLnl1bGRhc2hldkBleGFtcGxlLmNvbSIsInN0YXR1cyI6IkFDVElWRSIsInN1YiI6ImF2YXpiZWsueXVsZGFzaGV2QGV4YW1wbGUuY29tIiwiaWF0IjoxNzQwMzEyMDE1LCJleHAiOjE3NDAzOTg0MTV9.rtYWEKiDtIjku1xUZHEDroj2gFjmUDuClHuYwzxAD6Q

### Get Employee By ID
GET http://localhost:8080/employee/12
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJyb2xlIjoiQURNSU4iLCJ2aXNpYmxlIjp0cnVlLCJzdXJuYW1lIjoiRG9lIiwibmFtZSI6IkpvaG4iLCJpZCI6MSwicG9zaXRpb24iOiJTb2Z0d2FyZSBEZXZlbG9wZXIiLCJlbWFpbCI6ImpvaG4uZG9lQGV4YW1wbGUuY29tIiwic3RhdHVzIjoiQUNUSVZFIiwic3ViIjoiam9obi5kb2VAZXhhbXBsZS5jb20iLCJpYXQiOjE3Mzk0NDA4MTQsImV4cCI6MTczOTUyNzIxNH0.qgodvrJiHVFSguTnF4XXiNeWHtdnJSaMzx8hZh3zrrs

### Get Mee
GET http://localhost:8080/employee/getMe

### Get Employees By Department
GET http://localhost:8080/employee/1/department
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJyb2xlIjoiQURNSU4iLCJ2aXNpYmxlIjp0cnVlLCJzdXJuYW1lIjoiRG9lIiwibmFtZSI6IkpvaG4iLCJpZCI6MSwicG9zaXRpb24iOiJTb2Z0d2FyZSBEZXZlbG9wZXIiLCJlbWFpbCI6ImpvaG4uZG9lQGV4YW1wbGUuY29tIiwic3RhdHVzIjoiQUNUSVZFIiwic3ViIjoiam9obi5kb2VAZXhhbXBsZS5jb20iLCJpYXQiOjE3Mzk5ODM1NTYsImV4cCI6MTc0MDA2OTk1Nn0.Fsnz4_f7u9p8VXxpO7vf0vm1VH1EembLCQZVUjJmK5k


### Update Employee Role
PUT http://localhost:8080/employee/2/role
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJyb2xlIjoiQURNSU4iLCJ2aXNpYmxlIjp0cnVlLCJzdXJuYW1lIjoiRG9lIiwibmFtZSI6IkpvaG4iLCJpZCI6MSwicG9zaXRpb24iOiJTb2Z0d2FyZSBEZXZlbG9wZXIiLCJlbWFpbCI6ImpvaG4uZG9lQGV4YW1wbGUuY29tIiwic3RhdHVzIjoiQUNUSVZFIiwic3ViIjoiam9obi5kb2VAZXhhbXBsZS5jb20iLCJpYXQiOjE3MzkwMDQ0MjUsImV4cCI6MTczOTA5MDgyNX0.1jLmJQptcEEASvJAdmBBVSz9atVL4W-r0Gpuc8vjPCg

{
  "role": "USER"
}

### Update Employee Position
PUT http://localhost:8080/employee/2/position
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJyb2xlIjoiQURNSU4iLCJ2aXNpYmxlIjp0cnVlLCJzdXJuYW1lIjoiRG9lIiwibmFtZSI6IkpvaG4iLCJpZCI6MSwicG9zaXRpb24iOiJTb2Z0d2FyZSBEZXZlbG9wZXIiLCJlbWFpbCI6ImpvaG4uZG9lQGV4YW1wbGUuY29tIiwic3RhdHVzIjoiQUNUSVZFIiwic3ViIjoiam9obi5kb2VAZXhhbXBsZS5jb20iLCJpYXQiOjE3MzkwMDQ0MjUsImV4cCI6MTczOTA5MDgyNX0.1jLmJQptcEEASvJAdmBBVSz9atVL4W-r0Gpuc8vjPCg


{
  "position": "Senior Software Engineer"
}

### Update Employee Status
PUT http://localhost:8080/employee/2/status
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJyb2xlIjoiQURNSU4iLCJ2aXNpYmxlIjp0cnVlLCJzdXJuYW1lIjoiRG9lIiwibmFtZSI6IkpvaG4iLCJpZCI6MSwicG9zaXRpb24iOiJTb2Z0d2FyZSBEZXZlbG9wZXIiLCJlbWFpbCI6ImpvaG4uZG9lQGV4YW1wbGUuY29tIiwic3RhdHVzIjoiQUNUSVZFIiwic3ViIjoiam9obi5kb2VAZXhhbXBsZS5jb20iLCJpYXQiOjE3MzkwMDQ0MjUsImV4cCI6MTczOTA5MDgyNX0.1jLmJQptcEEASvJAdmBBVSz9atVL4W-r0Gpuc8vjPCg

{
  "status": "BLOCKED"
}

### Update Employee Department
PUT https://rttm.astiedu.uz/api/employee/1/department
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJyb2xlIjoiU1VQRVJBRE1JTiIsInZpc2libGUiOnRydWUsInN1cm5hbWUiOiJZdWxkYXNoZXYiLCJuYW1lIjoiQXZhemJlayIsImlkIjoxLCJwb3NpdGlvbiI6IldlYi1kaXpheW5lciIsImVtYWlsIjoiYXZhemJlay55dWxkYXNoZXZAZXhhbXBsZS5jb20iLCJzdGF0dXMiOiJBQ1RJVkUiLCJzdWIiOiJhdmF6YmVrLnl1bGRhc2hldkBleGFtcGxlLmNvbSIsImlhdCI6MTc0MDQyMjU4NywiZXhwIjoxNzQwNTA4OTg3fQ.OQ_in7TB5eA7ctxNErnfsknYxEz2PcvjqMGtAN3wmrU

{
  "departmentId": 1
}

### Update Employee
PUT http://localhost:8080/employee/12
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJyb2xlIjoiQURNSU4iLCJ2aXNpYmxlIjp0cnVlLCJzdXJuYW1lIjoiRG9lIiwibmFtZSI6IkpvaG4iLCJpZCI6MSwicG9zaXRpb24iOiJTb2Z0d2FyZSBEZXZlbG9wZXIiLCJlbWFpbCI6ImpvaG4uZG9lQGV4YW1wbGUuY29tIiwic3RhdHVzIjoiQUNUSVZFIiwic3ViIjoiam9obi5kb2VAZXhhbXBsZS5jb20iLCJpYXQiOjE3Mzk0NDA4MTQsImV4cCI6MTczOTUyNzIxNH0.qgodvrJiHVFSguTnF4XXiNeWHtdnJSaMzx8hZh3zrrs

{
  "name": "  asd",
  "surname": "asd ",
  "password": "asd"
}


### Get All Employees
GET http://213.230.99.253:8080/employee/all
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJyb2xlIjoiQURNSU4iLCJ2aXNpYmxlIjp0cnVlLCJzdXJuYW1lIjoiRG9lIiwiZGVwYXJ0bWVudElkIjoxLCJuYW1lIjoiSm9obiIsImlkIjoxLCJwb3NpdGlvbiI6IlNvZnR3YXJlIERldmVsb3BlciIsImVtYWlsIjoiam9obi5kb2VAZXhhbXBsZS5jb20iLCJzdGF0dXMiOiJBQ1RJVkUiLCJzdWIiOiJqb2huLmRvZUBleGFtcGxlLmNvbSIsImlhdCI6MTc0MDA2NjUyMywiZXhwIjoxNzQwMTUyOTIzfQ.582XA7kRmkNx0yeCI0CDyJ8JptR_h1Yfa1On9LRFS2c

### Soft Delete Employee
PUT http://213.230.99.253:8080/employee/6/wipe
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJyb2xlIjoiQURNSU4iLCJ2aXNpYmxlIjp0cnVlLCJzdXJuYW1lIjoiRG9lIiwiZGVwYXJ0bWVudElkIjoxLCJuYW1lIjoiSm9obiIsImlkIjoxLCJwb3NpdGlvbiI6IlNvZnR3YXJlIERldmVsb3BlciIsImVtYWlsIjoiam9obi5kb2VAZXhhbXBsZS5jb20iLCJzdGF0dXMiOiJBQ1RJVkUiLCJzdWIiOiJqb2huLmRvZUBleGFtcGxlLmNvbSIsImlhdCI6MTc0MDA2NjUyMywiZXhwIjoxNzQwMTUyOTIzfQ.582XA7kRmkNx0yeCI0CDyJ8JptR_h1Yfa1On9LRFS2c

{
  "visible": false
}



### Soft Delete Employee
PUT http://localhost:8080/employee/wipe
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJyb2xlIjoiQURNSU4iLCJ2aXNpYmxlIjp0cnVlLCJzdXJuYW1lIjoiRG9lIiwiZGVwYXJ0bWVudElkIjoxLCJuYW1lIjoiSm9obiIsImlkIjoxLCJwb3NpdGlvbiI6IlNvZnR3YXJlIERldmVsb3BlciIsImVtYWlsIjoiam9obi5kb2VAZXhhbXBsZS5jb20iLCJzdGF0dXMiOiJBQ1RJVkUiLCJzdWIiOiJqb2huLmRvZUBleGFtcGxlLmNvbSIsImlhdCI6MTc0MDA2NjUyMywiZXhwIjoxNzQwMTUyOTIzfQ.582XA7kRmkNx0yeCI0CDyJ8JptR_h1Yfa1On9LRFS2c


### Hard Delete Employee
DELETE http://localhost:8080/employee/2/delete
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJyb2xlIjoiQURNSU4iLCJ2aXNpYmxlIjp0cnVlLCJzdXJuYW1lIjoiRG9lIiwiZGVwYXJ0bWVudElkIjoxLCJuYW1lIjoiSm9obiIsImlkIjoxLCJwb3NpdGlvbiI6IlNvZnR3YXJlIERldmVsb3BlciIsImVtYWlsIjoiam9obi5kb2VAZXhhbXBsZS5jb20iLCJzdGF0dXMiOiJBQ1RJVkUiLCJzdWIiOiJqb2huLmRvZUBleGFtcGxlLmNvbSIsImlhdCI6MTc0MDA2NDIyNiwiZXhwIjoxNzQwMTUwNjI2fQ.9ze0DOh_qlIfftf6CEC8poSbfXQp31fNdaHB9J6RpBQ

### Get Paginated Employees
GET http://localhost:8080/employee/paged?page=1&size=10
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJyb2xlIjoiQURNSU4iLCJ2aXNpYmxlIjp0cnVlLCJzdXJuYW1lIjoiRG9lIiwibmFtZSI6IkpvaG4iLCJpZCI6MSwicG9zaXRpb24iOiJTb2Z0d2FyZSBEZXZlbG9wZXIiLCJlbWFpbCI6ImpvaG4uZG9lQGV4YW1wbGUuY29tIiwic3RhdHVzIjoiQUNUSVZFIiwic3ViIjoiam9obi5kb2VAZXhhbXBsZS5jb20iLCJpYXQiOjE3Mzg5NTMxNTAsImV4cCI6MTczOTAzOTU1MH0.nBt3NWPpHpQuwgJIPiWjKERWVrzO1j83wcTPDsaQjIY

### Filter Employees
POST http://localhost:8080/employee/filter?page=1&size=10
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJyb2xlIjoiQURNSU4iLCJ2aXNpYmxlIjp0cnVlLCJzdXJuYW1lIjoiRG9lIiwibmFtZSI6IkpvaG4iLCJpZCI6MSwicG9zaXRpb24iOiJTb2Z0d2FyZSBEZXZlbG9wZXIiLCJlbWFpbCI6ImpvaG4uZG9lQGV4YW1wbGUuY29tIiwic3RhdHVzIjoiQUNUSVZFIiwic3ViIjoiam9obi5kb2VAZXhhbXBsZS5jb20iLCJpYXQiOjE3Mzg5NTMxNTAsImV4cCI6MTczOTAzOTU1MH0.nBt3NWPpHpQuwgJIPiWjKERWVrzO1j83wcTPDsaQjIY

{

}
