### Xizmat yaratish
POST http://213.230.99.253:8080/offering
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJyb2xlIjoiQURNSU4iLCJ2aXNpYmxlIjp0cnVlLCJzdXJuYW1lIjoiRG9lIiwibmFtZSI6IkpvaG4iLCJpZCI6MSwicG9zaXRpb24iOiJTb2Z0d2FyZSBEZXZlbG9wZXIiLCJlbWFpbCI6ImpvaG4uZG9lQGV4YW1wbGUuY29tIiwic3RhdHVzIjoiQUNUSVZFIiwic3ViIjoiam9obi5kb2VAZXhhbXBsZS5jb20iLCJpYXQiOjE3NDAwNjg2MzIsImV4cCI6MTc0MDE1NTAzMn0.8b1sXeUtw2hgxEDjTw01QwAgF_uAfDoZAz510cLxoYM

{
  "title": "Sample Service",
  "description": "This is a sample offering",
  "departmentId": 2
}

### Barcha xizmatlarni olish
GET http://localhost:8080/offering/all
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJyb2xlIjoiQURNSU4iLCJ2aXNpYmxlIjp0cnVlLCJzdXJuYW1lIjoiRG9lIiwibmFtZSI6IkpvaG4iLCJpZCI6MSwicG9zaXRpb24iOiJTb2Z0d2FyZSBEZXZlbG9wZXIiLCJlbWFpbCI6ImpvaG4uZG9lQGV4YW1wbGUuY29tIiwic3RhdHVzIjoiQUNUSVZFIiwic3ViIjoiam9obi5kb2VAZXhhbXBsZS5jb20iLCJpYXQiOjE3MzkwMDQ3MjgsImV4cCI6MTczOTA5MTEyOH0.V-NL0olQN6hNuBqOMu-p8-ym0UdCx4X3Cq1g7zlu1AM

### ID bo'yicha xizmatni olish
GET http://localhost:8080/offering/1
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJyb2xlIjoiQURNSU4iLCJ2aXNpYmxlIjp0cnVlLCJzdXJuYW1lIjoiRG9lIiwibmFtZSI6IkpvaG4iLCJpZCI6MSwicG9zaXRpb24iOiJTb2Z0d2FyZSBEZXZlbG9wZXIiLCJlbWFpbCI6ImpvaG4uZG9lQGV4YW1wbGUuY29tIiwic3RhdHVzIjoiQUNUSVZFIiwic3ViIjoiam9obi5kb2VAZXhhbXBsZS5jb20iLCJpYXQiOjE3MzkwMDQ3MjgsImV4cCI6MTczOTA5MTEyOH0.V-NL0olQN6hNuBqOMu-p8-ym0UdCx4X3Cq1g7zlu1AM

### Bo'limga tegishli barcha xizmatlarni olish
GET http://localhost:8080/offering/2/department
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJyb2xlIjoiQURNSU4iLCJ2aXNpYmxlIjp0cnVlLCJzdXJuYW1lIjoiRG9lIiwibmFtZSI6IkpvaG4iLCJpZCI6MSwicG9zaXRpb24iOiJTb2Z0d2FyZSBEZXZlbG9wZXIiLCJlbWFpbCI6ImpvaG4uZG9lQGV4YW1wbGUuY29tIiwic3RhdHVzIjoiQUNUSVZFIiwic3ViIjoiam9obi5kb2VAZXhhbXBsZS5jb20iLCJpYXQiOjE3MzkwMDQ3MjgsImV4cCI6MTczOTA5MTEyOH0.V-NL0olQN6hNuBqOMu-p8-ym0UdCx4X3Cq1g7zlu1AM

### Xizmatni yangilash
PUT http://localhost:8080/offering/1
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJyb2xlIjoiQURNSU4iLCJ2aXNpYmxlIjp0cnVlLCJzdXJuYW1lIjoiRG9lIiwibmFtZSI6IkpvaG4iLCJpZCI6MSwicG9zaXRpb24iOiJTb2Z0d2FyZSBEZXZlbG9wZXIiLCJlbWFpbCI6ImpvaG4uZG9lQGV4YW1wbGUuY29tIiwic3RhdHVzIjoiQUNUSVZFIiwic3ViIjoiam9obi5kb2VAZXhhbXBsZS5jb20iLCJpYXQiOjE3MzkwMDQ3MjgsImV4cCI6MTczOTA5MTEyOH0.V-NL0olQN6hNuBqOMu-p8-ym0UdCx4X3Cq1g7zlu1AM

{
  "name": "Updated Service",
  "description": "Updated description",
  "departmentId": 2
}

### Xizmatga bo'lim ID sini yangilash
PUT http://localhost:8080/offering/1/department
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJyb2xlIjoiQURNSU4iLCJ2aXNpYmxlIjp0cnVlLCJzdXJuYW1lIjoiRG9lIiwibmFtZSI6IkpvaG4iLCJpZCI6MSwicG9zaXRpb24iOiJTb2Z0d2FyZSBEZXZlbG9wZXIiLCJlbWFpbCI6ImpvaG4uZG9lQGV4YW1wbGUuY29tIiwic3RhdHVzIjoiQUNUSVZFIiwic3ViIjoiam9obi5kb2VAZXhhbXBsZS5jb20iLCJpYXQiOjE3MzkwMDQ3MjgsImV4cCI6MTczOTA5MTEyOH0.V-NL0olQN6hNuBqOMu-p8-ym0UdCx4X3Cq1g7zlu1AM

{
  "departmentId": 2
}

### Xizmatni vaqtincha yashirish
PATCH http://localhost:8080/offering/1/wipe
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJyb2xlIjoiQURNSU4iLCJ2aXNpYmxlIjp0cnVlLCJzdXJuYW1lIjoiRG9lIiwibmFtZSI6IkpvaG4iLCJpZCI6MSwicG9zaXRpb24iOiJTb2Z0d2FyZSBEZXZlbG9wZXIiLCJlbWFpbCI6ImpvaG4uZG9lQGV4YW1wbGUuY29tIiwic3RhdHVzIjoiQUNUSVZFIiwic3ViIjoiam9obi5kb2VAZXhhbXBsZS5jb20iLCJpYXQiOjE3MzkwMDQ3MjgsImV4cCI6MTczOTA5MTEyOH0.V-NL0olQN6hNuBqOMu-p8-ym0UdCx4X3Cq1g7zlu1AM

{
  "visible": true
}

### Xizmatni o'chirish
DELETE http://localhost:8080/offering/1
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJyb2xlIjoiQURNSU4iLCJ2aXNpYmxlIjp0cnVlLCJzdXJuYW1lIjoiRG9lIiwibmFtZSI6IkpvaG4iLCJpZCI6MSwicG9zaXRpb24iOiJTb2Z0d2FyZSBEZXZlbG9wZXIiLCJlbWFpbCI6ImpvaG4uZG9lQGV4YW1wbGUuY29tIiwic3RhdHVzIjoiQUNUSVZFIiwic3ViIjoiam9obi5kb2VAZXhhbXBsZS5jb20iLCJpYXQiOjE3MzkwMDQ3MjgsImV4cCI6MTczOTA5MTEyOH0.V-NL0olQN6hNuBqOMu-p8-ym0UdCx4X3Cq1g7zlu1AM

### Xizmatlarni sahifalab olish
GET http://localhost:8080/offering/paged?page=1&size=10
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJyb2xlIjoiQURNSU4iLCJ2aXNpYmxlIjp0cnVlLCJzdXJuYW1lIjoiRG9lIiwibmFtZSI6IkpvaG4iLCJpZCI6MSwicG9zaXRpb24iOiJTb2Z0d2FyZSBEZXZlbG9wZXIiLCJlbWFpbCI6ImpvaG4uZG9lQGV4YW1wbGUuY29tIiwic3RhdHVzIjoiQUNUSVZFIiwic3ViIjoiam9obi5kb2VAZXhhbXBsZS5jb20iLCJpYXQiOjE3MzkwMDQ3MjgsImV4cCI6MTczOTA5MTEyOH0.V-NL0olQN6hNuBqOMu-p8-ym0UdCx4X3Cq1g7zlu1AM

### Filtr bo'yicha xizmatlarni olish
POST http://localhost:8080/offering/filter?page=1&size=10
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJyb2xlIjoiQURNSU4iLCJ2aXNpYmxlIjp0cnVlLCJzdXJuYW1lIjoiRG9lIiwibmFtZSI6IkpvaG4iLCJpZCI6MSwicG9zaXRpb24iOiJTb2Z0d2FyZSBEZXZlbG9wZXIiLCJlbWFpbCI6ImpvaG4uZG9lQGV4YW1wbGUuY29tIiwic3RhdHVzIjoiQUNUSVZFIiwic3ViIjoiam9obi5kb2VAZXhhbXBsZS5jb20iLCJpYXQiOjE3MzkwMDQ3MjgsImV4cCI6MTczOTA5MTEyOH0.V-NL0olQN6hNuBqOMu-p8-ym0UdCx4X3Cq1g7zlu1AM

{

}
